backend:
  name: github
  repo: zuratech-inc/gystservices.ca
  branch: main

media_folder: "src/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "src/content/pages/index.md"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "page.njk" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Event Date", name: "eventDate", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
